### ISSUE TITLE
License regkey parameter missing for BYOL license type

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-google-gdm-templates-v2#1]
## Do you already have an issue opened with F5 support?
No

## Description
User wants to deploy BYOL license type. Current example does not ask for a license regkey. There is nothing in runtime init example yaml files for a rendered regkey. The example yaml files have hard coded reg keys of AAAAA-BBBBB-CCCCC-DDDDD-EEEE.

## Template
all

## Severity Level
3

**Comment by JeffGiroux** [comment]
similar to AWS templates https://github.com/F5Networks/f5-aws-cloudformation-v2/issues/13

**Comment by shyawnkarim** [comment]
Thanks for your suggestion. A separate BYOL Quickstart template would make things easier for users who are trying things out. This enhancement is now being tracked with internal ID, ESECLDTPLT-2994.

**Comment by shyawnkarim** [comment]
Closing.

Our team discussed this idea and the consensus was not to add this since it would create more management overhead/clutter. Additionally, the README does cover how to modify a template.
