### ISSUE TITLE
typo in troubleshoot section for failover-example

### ISSUE THREAD

**Issue by Dvirus89** [F5Networks/f5-google-gdm-templates-v2#12]
## Documentation link
 https://github.com/F5Networks/f5-google-gdm-templates-v2/tree/main/examples/failover#troubleshooting-steps
>/var/log/cloud/bigipRuntimeInit.log: This file contains events logged by the f5-bigip-runtime-init onboarding utility. If the configuration is invalid causing onboarding to fail, you will see those events logged here. If deployment is successful, you will see an event with the body "All operations completed successfully".
 
## Describe the problem
 There is a typo in the file path: /var/log/cloud/bigipRuntimeInit.log
 
## Suggested fix
 
It should be a capital "i" like this: /var/log/cloud/bigIpRuntimeInit.log (bigIp and not bigip)

**Comment by shyawnkarim** [comment]
Thanks for reporting this issue. We are now tracking this with internal ID ESECLDTPLT-3166.

**Comment by shyawnkarim** [comment]
Closing. This issue was resolved with [Release 2.5.0.0](https://github.com/F5Networks/f5-google-gdm-templates-v2/releases/tag/v2.5.0.0).
