### ISSUE TITLE
BigIP5 - Not able to login

### ISSUE THREAD

**Issue by ashishbhutani2001** [F5Networks/f5-google-gdm-templates-v2#19]
## Describe the bug

I followed the steps outlined for Quickstart 3 NIC F5. The  deployment was successful but I am not able to login. Tried all option like admin/admin, admin/default, admin/instance_id,  quickstart/instance_id etc. Even tried changing the username to admin rom the setting option of SSH console but its still prompting for username.

 
What's the default credential for Quickstart F5 3 Nic instance.

**Comment by mikeshimkus** [comment]
Hi @ashishbhutani2001, after a successful deployment the admin password should be the instance ID of the BIG-IP VM, per this command: _gcloud deployment-manager manifests describe --deployment=${DEPLOYMENT_NAME} --format="value(layout)" | yq '.resources[0].outputs[] | select(.name | contains("bigIpInstanceId")).finalValue'_

 If that isn't working, you can login using admin and a private key that corresponds to a public key in your Google Cloud project (all the keys in your project should be copied to the instance by default). 

Then you can check that the deployment script successfully updated the password by running this from the BIG-IP shell:

cat /config/cloud/bigIpRuntimeInit.log

**Comment by ashishbhutani2001** [comment]
Thanks @mikeshimkus for your reply. Can you recheck the command syntax as I am getting below error.

**Command:**  gcloud deployment-manager manifests describe --deployment=f5-9 --format="value(layout)" | yq '.resources[0].outputs[] | select(.name | contains("bigIpInstanceId")).finalValue'                                                                                                                                                      

**Error:** -bash: yq: command not found

**Comment by mikeshimkus** [comment]
You'll need to install yq, see https://github.com/F5Networks/f5-google-gdm-templates-v2/tree/main/examples/quickstart#accessing-the-big-ip

Or you can use the Google Cloud console to go to the VM instance and click Basic Information>Instance Id

**Comment by ashishbhutani2001** [comment]
@mikeshimkus , tried both the steps you mentioned but it sill not working and prompting for credentials. 
I even installed a new instance but its giving same authentication issue.
Someone mentioned to change the username while connecting to SSH from within the GCP console.  SSH within Google console connects to eth0 of F5 so I  allowed port 22 and source 0.0.0.0/0 but SSH is not working on eth0 (firewall logs on eth0 showing the traffic is allowed). Could this be related to default route within F5 as we cannot have 2 default route pointing to 2 different Nic (ssh to eth1 is working from internet)? I don't know if Quickstart add multiple defaults routes as part of the scripts.

**Comment by mikeshimkus** [comment]
@ashishbhutani2001 If the deployment succeeded you will not be able to connect to management via console SSH to eth0, since eth1 is the management interface (due to routing only being applied to eth0, the external BIG-IP NIC must use it).

Installation of the public keys happens before any template configuration, perhaps try uploading a new key to your project and connecting to ssh using that key as admin?

**Comment by ashishbhutani2001** [comment]
@mikeshimkus , thanks for all your help. Uploading a new key fixed the issue.
