### ISSUE TITLE
No clear info on HA failover on GCP

### ISSUE THREAD

**Issue by aymanelbacha** [F5Networks/f5-google-gdm-templates-v2#22]
## Documentation link
 
https://community.f5.com/kb/technicalarticles/failing-faster-in-the-cloud/281744
 
## Describe the problem
 
Steps are not clear, need to share the configuration steps on both GCP and BIG-IP
Although following it and applying the same configuration mentioned on the video has not yielded with any success to failover
 
## Suggested fix
 
Send an updated document to follow for HA on GCP

**Comment by mikeshimkus** [comment]
Hi @aymanelbacha, the CFE documentation for Google is here: https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/userguide/gcp.html

**Comment by mikeshimkus** [comment]
The one I shared is the official document.
