### ISSUE TITLE
GCP Client Secret

### ISSUE THREAD

**Issue by huzer1** [F5Networks/f5-google-gdm-templates-v2#24]
## Describe the bug
 In the runtime init, it appears there's something wrong with the  GCP stored password. The password I'm using is
Jk198676!
(I won't use this password again...)

I created the password using the command from the documentation. 
`echo -n 'Jk198676!' | gcloud secrets create mySecretId --data-file=- ; history -d $(history 1)`

 
## Expected behavior
 
A successful run of runtime init
 
## Current behavior

 2024-05-20T20:47:59.385Z [3798]: error: GCP Cloud Client secret id mySecretId is the wrong format

 
## Steps to reproduce
 
I deployed the failover GCP template with the bare minimum settings. Full network stack and application. 
 https://github.com/F5Networks/f5-google-gdm-templates-v2/tree/main/examples/failover

 
## Your Environment
 
Test environment currently.

**Comment by mikeshimkus** [comment]
Hi @huzer1, can you share the input parameters file you used to deploy, specifically what was used for bigIpSecretId: https://github.com/F5Networks/f5-google-gdm-templates-v2/blob/d543fb234672ec2246ddaa512c69a5d940a24217/examples/failover/sample_failover.yaml#L91

And what was saved in /config/cloud/secret_id on the BIG-IPs?

**Comment by huzer1** [comment]
It was `mySecretId` 

I couldn't log into the BIG-IP's to find that file.

**Comment by mikeshimkus** [comment]
You should be able to login as admin with any SSH key that was in your Google Cloud project when you deployed.

**Comment by huzer1** [comment]
The contents of /config/cloud/secret_id
mySecretId

**Comment by mikeshimkus** [comment]
I see the problem now, our regex doesn't account for uppercase: https://github.com/F5Networks/f5-bigip-runtime-init/blob/2c560d743669c251ab50d03cf19d2404600195c4/src/lib/cloud/gcp/cloudClient.ts#L79C36-L79C55

For now you should be able to create the secret with the name "mysecretid" instead.

**Comment by huzer1** [comment]
Thanks, @mikeshimkus! I'm not sure which is proper, should I closed it as completed?

**Comment by mikeshimkus** [comment]
I created internal issue EC-515 against runtime init for this. You can close this as it's not a template issue per se.
