### ISSUE TITLE
RESOURCE ERROR when deploying sample_autoscale.yaml: PERMISSION DENIED

### ISSUE THREAD

**Issue by leondelyon3** [F5Networks/f5-google-gdm-templates-v2#3]
## Description
Deploying the sample_autoscale.yaml, and I am getting the following error:

ERROR: (gcloud.deployment-manager.deployments.create) Error in Operation [operation-1645794399517-5d8d75e8e7b52-cfe6b6b9-732c98a2]: errors:
- code: **RESOURCE_ERROR**
  location: /deployments/bigip-autoscale/resources/myuniqstrbigipaccessrole
  message: "{\"ResourceType\":\"gcp-types/iam-v1:projects.roles\",\"ResourceErrorCode\"\
    :\"403\",\"ResourceErrorMessage\":{\"code\":403,\"message\":\"You don't have permission\
    \ to create a role in projects/f5-gcs-1306-gs-emea-consult.\",\"status\":\"PERMISSION_DENIED\"\
    ,\"statusMessage\":\"Forbidden\",\"requestPath\":\"https://iam.googleapis.com/v1/projects/f5-gcs-1306-gs-emea-consult/roles\"\
    ,\"httpMethod\":\"POST\"}}"

FYI deploying the sample_quickstart.yaml was working fine without any error.
On top of that I can create role via cli :
gcloud iam roles create lionelAdmin --project=f5-gcs-1306-gs-emea-consult\
>   --title="My Company Admin" --description="My custom role description." \
>   --permissions=iam.roles.get,iam.roles.list --stage=ALPHA
Created role [lionelAdmin].
description: My custom role description.
etag: BwXY1zx8rUs=
includedPermissions:
- iam.roles.get
- iam.roles.list
name: projects/f5-gcs-1306-gs-emea-consult/roles/lionelAdmin
stage: ALPHA
title: My Company Admin

## Template
use sample_autoscale.yaml:
`imports:
  - path: autoscale.py
  - path: ../../modules/access/access.py
  - path: ../../modules/application/application.py
  - path: ../../modules/bigip-autoscale/bigip_autoscale.py
  - path: ../../modules/dag/dag.py
  - path: ../../modules/network/network.py
resources:
  - name: autoscale-py
    type: autoscale.py
    properties:
      ### (OPTIONAL) The docker container you like to deploy for the demo application.
      appContainerName: f5devcentral/f5-demo-app:latest
      ### (OPTIONAL) Application label.
      application: f5app
      ### (OPTIONAL): Number of seconds Google Autoscaler waits to start checking BIG-IP instances on first boot.
      bigIpCoolDownPeriodSec: 60
      ### (OPTIONAL) Supply a URL to the bigip-runtime-init configuration file in YAML or JSON format.
      bigIpRuntimeInitConfig: >-
        https://raw.githubusercontent.com/F5Networks/f5-google-gdm-templates-v2/v1.0.0.0/examples/autoscale/bigip-configurations/runtime-init-conf-payg.yaml
      ### (OPTIONAL) Supply a URL for the bigip-runtime-init package.
      bigIpRuntimeInitPackageUrl: >-
        https://cdn.f5.com/product/cloudsolutions/f5-bigip-runtime-init/v1.3.2/dist/f5-bigip-runtime-init-1.3.2-1.gz.run
      ### (OPTIONAL) The BIG-IP image name to deploy. If you would like to view all available images, run the following command from the **gcloud** command line: ```gcloud compute images list --project f5-7626-networks-public --filter="name~f5"```
      bigIpImageName: f5-bigip-16-1-0-0-0-19-payg-awf-plus-25mbps-210623021328
      ### (OPTIONAL) Version of the instance template to create. When updating deployment properties of the BIG-IP instances, you must provide a unique value for this parameter.
      bigIpInstanceTemplateVersion: 1
      ### (OPTIONAL) Instance type assigned to BIG-IP, for example 'n1-standard-4'.
      bigIpInstanceType: n1-standard-4
      ### (OPTIONAL): High CPU Percentage threshold to begin scaling out BIG-IP VE instances.
      bigIpScaleOutCpuThreshold: 0.8
      ### (OPTIONAL): Maximum number of BIG-IP instances that can be created in the Auto Scale Group.
      bigIpScalingMaxSize: 8
      ### (OPTIONAL): Minimum number of BIG-IP instances you want available in the Auto Scale Group.
      bigIpScalingMinSize: 1
      ### (OPTIONAL) Cost Center label.
      cost: f5cost
      ### (OPTIONAL) Environment Center label.
      environment: f5env
      ### (OPTIONAL) Owner label.
      owner: f5owner
      ### (OPTIONAL) Group label.
      group: f5group
      ### (OPTIONAL) Provision Public IP addresses for the BIG-IP Management interface. By default, this is set to true. If set to false, the solution will deploy a bastion host instead in order to provide access.
      provisionPublicIp: true
      ### (OPTIONAL) Enter the Google Region in which you want to deploy BIG-IP, for example 'us-west1'.
      region: us-west1
      ### (REQUIRED) This parameter restricts network access to the web application.
      # Provide a yaml list of addresses or networks in CIDR notation, for example, '- 55.55.55.55/32' for a host, '- 10.0.0.0/8' for a network, etc.
      restrictedSrcAddressApp:
        - 0.0.0.0/0
      ### (REQUIRED) This parameter restricts network access to the BIG-IP's management interface.
      # Provide a yaml list of addresses or networks in CIDR notation, for example, '- 55.55.55.55/32' for a host, '- 10.0.0.0/8' for a network, etc.
      # NOTE: If using a Bastion Host (when ProvisionPublicIp = false), you must also include the Bastion's source network as in the example below (w/ RFC 1918 block).
      restrictedSrcAddressMgmt:
        - 10.0.0.0/8
      ### (OPTIONAL) A prefix that will be used to name template resources. Because some resources require globally unique names, we recommend using a unique value.
      uniqueString: myuniqstr
      ### (OPTIONAL) This specifies when to add dependency statements to the autoscale related resources. By default, this is set to false. Specify false when first deploying and right before deleting. Specify true when updating the deployment. See README for more details.
      update: false
      ### (OPTIONAL) Enter the Google availability zone where you want to deploy the BIG-IP VE instance, for example 'us-west1-a'.
      zone: us-west1-a
`

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: <2>

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by JeffGiroux** [comment]
status update...deployment has passed access.py module !!!!!! The fix is to adjust the properties on the project service account for project-number@cloudservices.gserviceaccount.com. Must add "Role Admin" and "Project IAM Admin". The included service account already has "Editor" but that is not enough per Google Deployment Manager instructions for this autoscale repo. Additional access is needed.

reference...
https://cloud.google.com/deployment-manager/docs/access-control#access_control_for

**Comment by leondelyon3** [comment]
I've implemented the changes, and ... it works. :)
I think it should be part of the prerequisite doc section.
Thanks.

**Comment by shyawnkarim** [comment]
We know our documentation is lacking in this area and already have a story in our backlog to audit IAM roles, for all three public clouds, so that we can provide more guidance. The internal ID for it is ESECLDTPLT-2957.

**Comment by shyawnkarim** [comment]
Closing.

The documentation was updated with [Release 2.2.0.0](https://github.com/F5Networks/f5-google-gdm-templates-v2/releases/tag/v2.2.0.0).
