### ISSUE TITLE
Permissions problem with deploying sample_failover.yaml

### ISSUE THREAD

**Issue by curtkersey** [F5Networks/f5-google-gdm-templates-v2#4]
## Describe the bug
 
I am deploying the failover example.  I have added the Project IAM Admin and Secret Manager Admin permissions to the Google APIs Service Agent service account; however, when I run the template, I am getting a permissions denied when creating the custom role.  Output from Deployments Manager:

 {"ResourceType":"gcp-types/iam-v1:projects.roles","ResourceErrorCode":"403","ResourceErrorMessage":{"code":403,"message":"You don't have permission to create a role in projects/f5-gcs-4261-sales-na-se.","status":"PERMISSION_DENIED","statusMessage":"Forbidden","requestPath":"https://iam.googleapis.com/v1/projects/f5-gcs-4261-sales-na-se/roles","httpMethod":"POST"}} 

I have confirmed that the Google APIs Service Agent service account has the permissions listed in README.
 
## Expected behavior
 
The custom service account and role should be created based on permissions granted.
 
## Current behavior
 
It fails -- error message above.
 
## Possible solution
 
TBD - I could have something wrong.  I have confirmed that my service account (for which I have authenticated) has the permissions listed in README also.
 
## Steps to reproduce
 
Using the sample_failover.yaml file in the repo with the only changes being:
bigIpInstanceType: n1-standard-8
region: us-east1
uniqueString: xyz
zone: us-east1-b
restrictedSrcAddressApp:
 - 0.0.0.0/0
restrictedSrcAddressMgmt:
  - 0.0.0.0/0
 
## Screenshots
 
None provided.
 
## Context
 
Trying to deploy the sample failover example, so I can customize and demonstrate usage.
 
## Your Environment
 
Ubuntu 18.04LTS server running in GCP. Using gcloud commands to deploy sample.

**Comment by curtkersey** [comment]
FYI - adding the Role Admin to the Google APIs Service Agent service account as described in https://github.com/F5Networks/f5-google-gdm-templates-v2/issues/3 resolves this issue.  The docs for sample failover should be updated to include these permissions as well.

**Comment by shyawnkarim** [comment]
Closing.

We updated the roles needed for deployment with [Release 2.2.0.0](https://github.com/F5Networks/f5-google-gdm-templates-v2/releases/tag/v2.2.0.0).
