### ISSUE TITLE
Example - failover: BIG-IPs not in HA relationship after running template

### ISSUE THREAD

**Issue by curtkersey** [F5Networks/f5-google-gdm-templates-v2#6]
## Describe the bug
This could be related to https://github.com/F5Networks/f5-google-gdm-templates-v2/issues/5.  Once the template is done, the BIG-IPs are in standalone mode with no configuration.
 
## Expected behavior
BIG-IPs should be in HA relationship.
 
## Current behavior
BIG-IPs are in standalone mode with no configuration on GUI.
 
## Possible solution
TBD
 
## Steps to reproduce
Ran the template -- same as in https://github.com/F5Networks/f5-google-gdm-templates-v2/issues/5. 
 
 
## Context
Trying to create HA pair of BIG-IPs using the templates.
 
## Your Environment
Same as in https://github.com/F5Networks/f5-google-gdm-templates-v2/issues/5.

**Comment by f5-applebaum** [comment]
Related to Issue #5. This is because BIG-IPs couldn't get the secret/ password used to form cluster.

**Comment by curtkersey** [comment]
Closing this issue based on getting things working.  See the resolution in the following Issues to see the root cause of my problems:
https://github.com/F5Networks/f5-google-gdm-templates-v2/issues/5
https://github.com/F5Networks/f5-google-gdm-templates-v2/issues/7
