### ISSUE TITLE
Docs: old links pointing to f5devcentral BIG-IP runtime init repo

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-google-gdm-templates-v2#8]
## Documentation link
 
All README files
 
## Describe the problem
 
Multilple links within the README of the v2 templates reference BIG-IP runtime init...but they reference the F5devcentral org repo instead of the F5Networks org repo.  

## Suggested fix
 
Please scrub all links and update accordingly across all v1 and v2 templates.

**Comment by shyawnkarim** [comment]
Thanks for reporting this. We are tracking this with internal ID, ESECLDTPLT-3074, and will have these updated for our next release.

**Comment by shyawnkarim** [comment]
Closing.

This fix was included with R[elease 3.16.0](https://github.com/F5Networks/f5-google-gdm-templates/releases/tag/v3.16.0).
